<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-ESD1NT2A" failures="1" tests="1" name="Test" time="36.201" errors="0" timestamp="2022-11-24T16:17:37 IST">
  <testcase classname="com.qa.tests.LoginTests" name="invalidUserName" time="1.54">
    <failure type="org.json.JSONException" message="JSONObject[&amp;quot;invalidUse&amp;quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["invalidUse"] not found.
at org.json.JSONObject.get(JSONObject.java:570)
at org.json.JSONObject.getJSONObject(JSONObject.java:780)
at com.qa.tests.LoginTests.invalidUserName(LoginTests.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- invalidUserName -->
  <testcase classname="com.qa.tests.LoginTests" name="successfulLogin" time="0.0">
    <ignored/>
  </testcase> <!-- successfulLogin -->
  <testcase classname="com.qa.tests.LoginTests" name="invalidPassword" time="0.0">
    <ignored/>
  </testcase> <!-- invalidPassword -->
</testsuite> <!-- Test -->
